CREATE TABLE IF NOT EXISTS weather_current (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grid_x SMALLINT NOT NULL,
  grid_y SMALLINT NOT NULL,
  base_date VARCHAR(8) NOT NULL,
  base_time VARCHAR(4) NOT NULL,
  temperature DECIMAL(4,1),
  humidity SMALLINT,
  rainfall DECIMAL(5,1),
  wind_direction SMALLINT,
  wind_speed DECIMAL(4,1),
  wind_u DECIMAL(4,1),
  wind_v DECIMAL(4,1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_grid_time (grid_x, grid_y, base_date, base_time),
  INDEX idx_base_datetime (base_date, base_time)
);

CREATE TABLE IF NOT EXISTS weather_ultra (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grid_x SMALLINT NOT NULL,
  grid_y SMALLINT NOT NULL,
  fcst_date VARCHAR(8) NOT NULL,
  fcst_time VARCHAR(4) NOT NULL,
  base_date VARCHAR(8) NOT NULL,
  base_time VARCHAR(4) NOT NULL,
  temperature DECIMAL(4,1),
  humidity SMALLINT,
  sky TINYINT,
  pty TINYINT,
  rainfall DECIMAL(5,1),
  lightning DECIMAL(5,1),
  wind_direction SMALLINT,
  wind_speed DECIMAL(4,1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_grid_fcst (grid_x, grid_y, fcst_date, fcst_time),
  INDEX idx_fcst_datetime (fcst_date, fcst_time),
  INDEX idx_base_datetime (base_date, base_time)
);

CREATE TABLE IF NOT EXISTS weather_short (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grid_x SMALLINT NOT NULL,
  grid_y SMALLINT NOT NULL,
  fcst_date VARCHAR(8) NOT NULL,
  fcst_time VARCHAR(4) NOT NULL,
  base_date VARCHAR(8) NOT NULL,
  base_time VARCHAR(4) NOT NULL,
  temperature DECIMAL(4,1),
  temp_min DECIMAL(4,1),
  temp_max DECIMAL(4,1),
  humidity SMALLINT,
  sky TINYINT,
  pty TINYINT,
  pop SMALLINT,
  rainfall VARCHAR(20),
  snowfall VARCHAR(20),
  wind_direction SMALLINT,
  wind_speed DECIMAL(4,1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_grid_fcst (grid_x, grid_y, fcst_date, fcst_time),
  INDEX idx_fcst_datetime (fcst_date, fcst_time),
  INDEX idx_base_datetime (base_date, base_time)
);
